name: IOBookcase
main: com.lonelydime.IOBookcase.IOBookcase
version: 1.3
website: https://github.com/lonelydime
author: lonelydime
description: >
             Allows players to read/write from bookcases.