# IOBookcase's configuration file
# -----
# drop-bookcase: Controls if destroyed bookcases are dropped
# random-text: Controls if empty bookcases issues random text taken from the books.txt
# send-msg-on-empty: Controls weather 'msg-empty-bookcase' should be send or not
# -----
# You may configure every message the plugin issues below.
drop-bookcase: true
random-text: true
send-msg-on-empty: true
msg-empty-bookcase: 'This bookcase is empty.'
msg-pick-book: 'You pick up a book...'
msg-notify-written: 'Text written to line'
msg-notify-deleted: 'Bookcase unregistered.'
msg-notify-found: 'Bookcase was imported.'
msg-error-lines: 'Only lines 1-10 allowed.'
msg-error-format: 'The format is @line linenumber [color].'
msg-error-exeption: 'Unable to write text: '
msg-error-color: 'You selected a none valid color: Defaulting to white.'
msg-error-import: 'Could not find the case''s name, make sure your format is correct.'
msg-error-to-few-arguments: 'To few Arguments. Try again.'
msg-error-find-file: Unable to find the import.xml. Please contat the serveradmin.
msg-error-fetch-line: Failed to fetch a line from the books file.